# Generated by Django 2.1.1 on 2018-09-03 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_reason', models.CharField(max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Group')),
            ],
        ),
        migrations.CreateModel(
            name='PreName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название типа узла', max_length=30, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Тип узла',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Используйте формат: <em>XXX.XXX.XXX.XXX</em>.', max_length=30, verbose_name='Название узла')),
                ('edit_date', models.DateField(auto_now=True, verbose_name='Последнее изменение')),
                ('titul_file', models.FileField(blank=True, upload_to='', verbose_name='Фото титульной страницы')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('prename', models.ForeignKey(help_text='Обязательное поле', max_length=30, on_delete=django.db.models.deletion.CASCADE, to='catalog.PreName', verbose_name='Тип узла')),
            ],
            options={
                'verbose_name_plural': 'Узлы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_invites', to='catalog.Unit'),
        ),
        migrations.AddField(
            model_name='membership',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Unit'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='catalog.Membership', to='catalog.Unit'),
        ),
    ]
