# Generated by Django 2.1.1 on 2018-09-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
    ]
