# Generated by Django 2.1.1 on 2018-08-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymodel',
            options={'ordering': ['name'], 'verbose_name_plural': 'Узлы'},
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='stuff',
            field=models.ManyToManyField(blank=True, to='catalog.MyModel'),
        ),
    ]
