# Generated by Django 2.1.1 on 2018-08-31 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180831_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prename',
            options={'ordering': ['name'], 'verbose_name_plural': 'Тип узла'},
        ),
        migrations.AddField(
            model_name='unit',
            name='edit_date',
            field=models.DateField(auto_now=True, verbose_name='Название узла'),
        ),
        migrations.AddField(
            model_name='unit',
            name='titul_file',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото титульной страницы'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='prename',
            field=models.ForeignKey(help_text='Обязательное поле', max_length=30, on_delete=django.db.models.deletion.CASCADE, to='catalog.PreName', verbose_name='Тип узла'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='stuff',
            field=models.ManyToManyField(blank=True, to='catalog.Unit', verbose_name='Вложенные узлы'),
        ),
    ]
