# Generated by Django 2.1.1 on 2018-09-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180904_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='part_weight',
            field=models.FloatField(verbose_name='Теоретический вес детали'),
        ),
    ]
