# Generated by Django 2.1.1 on 2018-09-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180904_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='text_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='prename',
            name='name',
            field=models.CharField(help_text='Название типа узла', max_length=30, unique=True, verbose_name='Название'),
        ),
    ]
