# Generated by Django 2.1.1 on 2018-09-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180901_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
    ]
