# Generated by Django 2.1.1 on 2018-09-10 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180904_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Shop'),
        ),
    ]
