# Generated by Django 2.1.1 on 2018-09-18 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180911_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbbrName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Аббревиатура узла', max_length=30, unique=True, verbose_name='Аббревиатура узла')),
            ],
            options={
                'verbose_name': 'аббревиатура',
                'verbose_name_plural': 'аббревиатуры',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='membershop',
            options={'verbose_name': 'вложенный цех', 'verbose_name_plural': 'вложенные цехи'},
        ),
        migrations.AlterField(
            model_name='detail',
            name='shop',
            field=models.ManyToManyField(related_name='related_to_shop', through='catalog.MemberShop', to='catalog.Shop'),
        ),
        migrations.AlterField(
            model_name='membershop',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='очередь'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(help_text='Используйте формат: <em>XXX.XXX.XXX.XXX</em>.', max_length=30, unique=True, verbose_name='Название узла'),
        ),
        migrations.AlterUniqueTogether(
            name='membershop',
            unique_together={('from_u', 'to_u')},
        ),
        migrations.AddField(
            model_name='unit',
            name='abbrname',
            field=models.ForeignKey(blank=True, help_text='Не обязательное поле', max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.AbbrName', verbose_name='Аббревиатура узла'),
        ),
    ]
