# Generated by Django 2.1.1 on 2018-09-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20180918_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='papnum',
            field=models.PositiveIntegerField(null=True, verbose_name='Номер папки'),
        ),
    ]
