# Generated by Django 2.1.1 on 2018-09-20 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_unit_papnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memberstandartdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'вложенное стандартное изделие',
                'verbose_name_plural': 'вложенные стандартные изделия',
            },
        ),
        migrations.CreateModel(
            name='StandartDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_num', models.CharField(max_length=50, unique=True, verbose_name='Обозначение')),
            ],
            options={
                'verbose_name': 'стандартная деталь',
                'verbose_name_plural': 'стандартные детали',
            },
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['name'], 'verbose_name': 'сборочная единица', 'verbose_name_plural': 'сборочные единицы'},
        ),
        migrations.AlterField(
            model_name='detail',
            name='nom_num',
            field=models.CharField(max_length=50, unique=True, verbose_name='Обозначение'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='abbrname',
            field=models.ForeignKey(blank=True, help_text='Например: ТСЦ', max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.AbbrName', verbose_name='Аббревиатура узла'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='detail',
            field=models.ManyToManyField(blank=True, related_name='related_to', through='catalog.Memberdetail', to='catalog.Detail'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='related_to', through='catalog.Membership', to='catalog.Unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(help_text='Используйте формат: <em>XXX.XXX.XXX.XXX</em>.', max_length=30, unique=True, verbose_name='Обозначение'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='papnum',
            field=models.PositiveIntegerField(blank=True, help_text='Оригинальный номер папки', null=True, unique=True, verbose_name='Номер папки'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='prename',
            field=models.ForeignKey(help_text='Например: "Стенка торцевая", "Звездочка приводная"', max_length=30, on_delete=django.db.models.deletion.CASCADE, to='catalog.PreName', verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='memberstandartdetail',
            name='from_u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_unit_to_standart_detail', to='catalog.Unit', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='memberstandartdetail',
            name='to_u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_standart_detail', to='catalog.StandartDetail', verbose_name='Вложенная стандартная деталь'),
        ),
        migrations.AddField(
            model_name='unit',
            name='standartdetail',
            field=models.ManyToManyField(blank=True, related_name='related_to', through='catalog.Memberstandartdetail', to='catalog.StandartDetail'),
        ),
        migrations.AlterUniqueTogether(
            name='memberstandartdetail',
            unique_together={('from_u', 'to_u')},
        ),
    ]
