# Generated by Django 2.1.1 on 2018-09-20 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20180920_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitContentPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.AlterModelOptions(
            name='memberdetail',
            options={'verbose_name': 'деталь', 'verbose_name_plural': 'детали'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'сборочная единица', 'verbose_name_plural': 'сборочные единицы'},
        ),
        migrations.AlterModelOptions(
            name='membershop',
            options={'verbose_name': 'цех', 'verbose_name_plural': 'цехи'},
        ),
        migrations.AlterModelOptions(
            name='memberstandartdetail',
            options={'verbose_name': 'стандартное изделие', 'verbose_name_plural': 'стандартные изделия'},
        ),
        migrations.AlterModelOptions(
            name='standartdetail',
            options={'verbose_name': 'стандартное изделие', 'verbose_name_plural': 'стандартные изделия'},
        ),
        migrations.AlterField(
            model_name='memberdetail',
            name='to_u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_detail', to='catalog.Detail', verbose_name='деталь'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='to_u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_unit', to='catalog.Unit', verbose_name='Сборочная единица'),
        ),
        migrations.AlterField(
            model_name='memberstandartdetail',
            name='to_u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_standart_detail', to='catalog.StandartDetail', verbose_name='Стандартное изделие'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='abbrname',
            field=models.ForeignKey(blank=True, help_text='Например: ТСЦ', max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.AbbrName', verbose_name='Аббревиатура'),
        ),
        migrations.AddField(
            model_name='unitcontentphoto',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.Unit'),
        ),
    ]
