# Generated by Django 2.1.1 on 2018-09-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20180920_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitcontentphoto',
            options={'verbose_name': 'содержание', 'verbose_name_plural': 'содержания'},
        ),
        migrations.RenameField(
            model_name='unitcontentphoto',
            old_name='location',
            new_name='unit',
        ),
    ]
