# Generated by Django 2.1.1 on 2018-09-21 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20180920_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitcontentphoto',
            options={'verbose_name': 'скан спецификации', 'verbose_name_plural': 'сканы спецификации'},
        ),
        migrations.RemoveField(
            model_name='unit',
            name='titul_file',
        ),
        migrations.AddField(
            model_name='unit',
            name='titul_image',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='Фото титульной страницы'),
        ),
        migrations.AlterField(
            model_name='unitcontentphoto',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unitimage', to='catalog.Unit'),
        ),
    ]
