# Generated by Django 2.1.1 on 2018-10-11 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20180921_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandartDetailCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Родитель стандартной детали',
                'verbose_name_plural': 'Родители стандартной детали',
            },
        ),
        migrations.AddField(
            model_name='standartdetail',
            name='standart_detail_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.StandartDetailCreator', verbose_name='Родитель стандартной детали'),
        ),
    ]
