# Generated by Django 2.1.1 on 2018-10-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20181011_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='standartdetail',
            name='edit_date',
            field=models.DateField(auto_now=True, verbose_name='Последнее изменение'),
        ),
        migrations.AddField(
            model_name='standartdetailcreator',
            name='edit_date',
            field=models.DateField(auto_now=True, verbose_name='Последнее изменение'),
        ),
    ]
